# coding: utf-8

"""
    Amsterdam Mail Service API.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amsterdam_mail_service_client.models.send404_response import Send404Response

class TestSend404Response(unittest.TestCase):
    """Send404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Send404Response:
        """Test Send404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Send404Response`
        """
        model = Send404Response()
        if include_optional:
            return Send404Response(
                message = 'Credentials not found. Did you add them using the /credentials endpoint?'
            )
        else:
            return Send404Response(
        )
        """

    def testSend404Response(self):
        """Test Send404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
