# coding: utf-8

"""
    Amsterdam Mail Service API.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amsterdam_mail_service_client.models.send200_response import Send200Response

class TestSend200Response(unittest.TestCase):
    """Send200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Send200Response:
        """Test Send200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Send200Response`
        """
        model = Send200Response()
        if include_optional:
            return Send200Response(
                message = ''
            )
        else:
            return Send200Response(
        )
        """

    def testSend200Response(self):
        """Test Send200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
