# coding: utf-8

"""
    Amsterdam Mail Service API.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amsterdam_mail_service_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.IsolatedAsyncioTestCase):
    """DefaultApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DefaultApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_preview(self) -> None:
        """Test case for preview

        Renders a preview of the mail that would be sent.
        """
        pass

    async def test_send(self) -> None:
        """Test case for send

        Sends mail using the provided input and the template on the server.
        """
        pass


if __name__ == '__main__':
    unittest.main()
