# coding: utf-8

"""
    Amsterdam Mail Service API.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amsterdam_mail_service_client.models.credentials_request import CredentialsRequest

class TestCredentialsRequest(unittest.TestCase):
    """CredentialsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CredentialsRequest:
        """Test CredentialsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CredentialsRequest`
        """
        model = CredentialsRequest()
        if include_optional:
            return CredentialsRequest(
                username = '01',
                password = '01'
            )
        else:
            return CredentialsRequest(
                username = '01',
                password = '01',
        )
        """

    def testCredentialsRequest(self):
        """Test CredentialsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
