services:
  openapi-generator-cli:
    image: openapitools/openapi-generator-cli:v7.13.0
    command:
      - "generate"
      - "-i"
      - "http://amsterdam-mail-service:8003/api-docs"
      - "-g"
      - "python"
      - "-o"
      - "/local"
      - "--package-name"
      - "amsterdam_mail_service_client"
      - "--git-host"
      - "github.com"
      - "--git-user-id"
      - "Amsterdam"
      - "--git-repo-id"
      - "amsterdam-mail-service-client"
      - "--library"
      - "asyncio"
    volumes:
      - ".:/local"
    depends_on:
      - amsterdam-mail-service

  amsterdam-mail-service-client:
    image: amsterdam/amsterdam-mail-service-client
    build:
      context: .
    volumes:
      - ".:/opt/amsterdam-mail-service-client"
    depends_on:
      - amsterdam-mail-service

  amsterdam-mail-service:
    image: amsterdam/amsterdam-mail-service:latest
    environment:
      PORT: 8003
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
    ports:
      - "8003:8003"
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
