# coding: utf-8

# flake8: noqa

"""
    Amsterdam Mail Service API.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from amsterdam_mail_service_client.api.default_api import DefaultApi

# import ApiClient
from amsterdam_mail_service_client.api_response import ApiResponse
from amsterdam_mail_service_client.api_client import ApiClient
from amsterdam_mail_service_client.configuration import Configuration
from amsterdam_mail_service_client.exceptions import OpenApiException
from amsterdam_mail_service_client.exceptions import ApiTypeError
from amsterdam_mail_service_client.exceptions import ApiValueError
from amsterdam_mail_service_client.exceptions import ApiKeyError
from amsterdam_mail_service_client.exceptions import ApiAttributeError
from amsterdam_mail_service_client.exceptions import ApiException

# import models into sdk package
from amsterdam_mail_service_client.models.preview_request import PreviewRequest
from amsterdam_mail_service_client.models.send200_response import Send200Response
from amsterdam_mail_service_client.models.send_request import SendRequest
